import time
import re

#Sliding window - overlapping
def soln1(sequence, binary):
  vowels = {"a", "e", "i", "o", "u"}
  sequence = list(sequence)
  for i, char in enumerate(sequence):
    if char in vowels:
      sequence[i] = "0"
    else:
      sequence[i] = "1"
  sequence = "".join(sequence)
  start = time.time()
  count = 0
  i, j = 0, len(binary)
  while j <= len(sequence):
    if sequence[i:j] == binary:
      count += 1
    i += 1
    j += 1
  print(f"{time.time()-start:.10f}")
  return count

#RegEx - non-overlapping
def soln2(sequence, binary):
  vowels = {"a", "e", "i", "o", "u"}
  sequence = list(sequence)
  for i, char in enumerate(sequence):
    if char in vowels:
      sequence[i] = "0"
    else:
      sequence[i] = "1"
  sequence = "".join(sequence)
  start = time.time()
  res = len(re.findall(binary, sequence))
  print(f"{time.time()-start:.10f}")
  return res


#8ms
if soln1("aaaaaaaaaaaaaaappppppazazazazazaazazazazazaazazazazazaazazpppppazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazaz", "010101010101") == 0:
  print("correct\n")

if soln2("aaaaaaaaaaaaaaappppppazazazazazaazazazazazaazazazazazaazazpppppazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazazazaazazazaz", "010101010101") == 0:
  print("correct\n")